const roomiesData = [
  {
    id: 1,
    name: "Ana García",
    occupation: "Estudiante de Psicología",
    avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
    birthday: "15 de Mayo",
    university: "Universidad Autónoma de Madrid",
    interests: ["Lectura", "Yoga", "Cocina"],
  },
  {
    id: 2,
    name: "Carlos Rodríguez",
    occupation: "Estudiante de Ingeniería",
    avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
    birthday: "22 de Septiembre",
    university: "Universidad Politécnica de Madrid",
    interests: ["Videojuegos", "Fútbol", "Programación"],
  },
  {
    id: 3,
    name: "Elena Martínez",
    occupation: "Estudiante de Medicina",
    avatar: "https://cdn.quasar.dev/img/avatar4.jpg",
    birthday: "7 de Enero",
    university: "Universidad Complutense de Madrid",
    interests: ["Música", "Voluntariado", "Cine"],
  },
  {
    id: 4,
    name: "David López",
    occupation: "Estudiante de Economía",
    avatar: "https://cdn.quasar.dev/img/avatar5.jpg",
    birthday: "30 de Noviembre",
    university: "Universidad Carlos III de Madrid",
    interests: ["Deportes", "Viajes", "Fotografía"],
  },
];

const eventsData = [
  {
    id: 1,
    title: "Limpiar la cocina",
    date: "2025-11-05",
    time: "10:00",
    type: "tarea",
    description: "Limpiar a fondo la cocina, incluyendo el horno y la nevera.",
    assignedTo: "Ana",
    bgcolor: "orange",
  },
  {
    id: 2,
    title: "Pagar el alquiler",
    date: "2025-11-01",
    time: "09:00",
    type: "pago",
    description: "Transferir el dinero del alquiler al propietario.",
    bgcolor: "red",
  },
  {
    id: 3,
    title: "Fiesta de cumpleaños de Carlos",
    date: "2025-11-20",
    time: "20:00",
    type: "evento",
    description: "Celebración del cumpleaños de Carlos en el salón común.",
    bgcolor: "green",
  },
  {
    id: 4,
    title: "Comprar suministros",
    date: "2025-11-10",
    time: "16:00",
    type: "tarea",
    description:
      "Comprar papel higiénico, detergente y otros suministros para el piso.",
    assignedTo: "Elena",
    bgcolor: "blue",
  },
  {
    id: 5,
    title: "Noche de películas",
    date: "2025-11-25",
    time: "21:00",
    type: "evento",
    description: "Noche de películas con todos los compañeros de piso.",
    bgcolor: "purple",
  },
  {
    id: 6,
    title: "Reunión para planificar la cena de Acción de Gracias",
    date: "2025-11-02",
    time: "19:00",
    type: "evento",
    description: "Decidir el menú, comprar los ingredientes y asignar tareas.",
    bgcolor: "brown",
  },
  {
    id: 7,
    title: "Limpiar el baño",
    date: "2025-11-15",
    time: "14:00",
    type: "tarea",
    description:
      "Limpiar a fondo el baño, incluyendo el inodoro, el lavabo y la ducha.",
    assignedTo: "Pedro",
    bgcolor: "orange",
  },
  {
    id: 8,
    title: "Pagar la factura de la luz",
    date: "2024-11-20",
    time: "15:00",
    type: "pago",
    description: "Realizar el pago de la factura de la luz.",
    bgcolor: "red",
  },
  {
    id: 9,
    title: "Salida al cine",
    date: "2024-11-28",
    time: "20:30",
    type: "evento",
    description: "Ir al cine a ver la última película.",
    bgcolor: "green",
  },
  {
    id: 10,
    title: "Día de limpieza general",
    date: "2024-11-08",
    time: "10:00",
    type: "tarea",
    description: "Limpiar todas las áreas comunes del piso.",
    assignedTo: "Todos",
    bgcolor: "blue",
  },
];

const pisoData = {
  direccion: "Calle Universidad, 123",
  codPostal: "28001",
  ciudad: "Madrid",
  caracteristicas: {
    bedrooms: 4,
    bathrooms: 2,
    area: "120 m²",
    furnished: "Sí",
    internet: "Fibra 300Mb",
    heating: "Calefacción central",
    airConditioning: "Sí",
  },
  roomies: [
    {
      id: 1,
      name: "Ana García",
      occupation: "Estudiante de Psicología",
      avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
    },
    {
      id: 2,
      name: "Carlos Rodríguez",
      occupation: "Estudiante de Ingeniería",
      avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
    },
    {
      id: 3,
      name: "Elena Martínez",
      occupation: "Estudiante de Medicina",
      avatar: "https://cdn.quasar.dev/img/avatar4.jpg",
    },
    {
      id: 4,
      name: "David López",
      occupation: "Estudiante de Economía",
      avatar: "https://cdn.quasar.dev/img/avatar5.jpg",
    },
  ],
  localizacion: "src/assets/Plano.png", // Reemplazar con un plano real
  servicios: [
    { name: "Supermercado", distance: "200m", icon: "shopping_cart" },
    { name: "Parada de Metro", distance: "500m", icon: "subway" },
    { name: "Gimnasio", distance: "1km", icon: "fitness_center" },
    { name: "Biblioteca", distance: "800m", icon: "local_library" },
    { name: "Parque", distance: "600m", icon: "park" },
    { name: "Farmacia", distance: "300m", icon: "local_pharmacy" },
  ],
};

const tasksData = [
  {
    id: 1,
    title: "Limpiar la cocina",
    description: "Limpiar la encimera, fregar los platos y barrer el suelo",
    assignedTo: "Ana García",
    dueDate: "2025-11-20",
    completed: false,
  },
  {
    id: 2,
    title: "Comprar suministros",
    description: "Comprar papel higiénico, detergente y bolsas de basura",
    assignedTo: "Carlos Rodríguez",
    dueDate: "2025-11-22",
    completed: false,
  },
  {
    id: 3,
    title: "Pagar la factura de internet",
    description: "Transferir el dinero para la factura mensual de internet",
    assignedTo: "Elena Martínez",
    dueDate: "2025-11-25",
    completed: true,
  },
];

const expensesData = [
  {
    id: 1,
    description: "Compra semanal",
    amount: 75.5,
    category: "Alimentación",
    paidBy: "Ana García",
    date: "2025-11-15",
  },
  {
    id: 2,
    description: "Factura de luz",
    amount: 60.0,
    category: "Servicios",
    paidBy: "Carlos Rodríguez",
    date: "2025-11-10",
  },
  {
    id: 3,
    description: "Netflix",
    amount: 11.99,
    category: "Entretenimiento",
    paidBy: "Elena Martínez",
    date: "2025-11-05",
  },
];

const shoppingItemsData = [
  {
    id: 1,
    name: "Leche",
    quantity: 2,
    unit: "litros",
    addedBy: "Ana García",
    purchased: false,
  },
  {
    id: 2,
    name: "Pan",
    quantity: 1,
    unit: "barra",
    addedBy: "Carlos Rodríguez",
    purchased: true,
  },
  {
    id: 3,
    name: "Huevos",
    quantity: 12,
    unit: "unidades",
    addedBy: "Elena Martínez",
    purchased: false,
  },
];

const userProfileData = {
  name: "Ana García",
  alias: "AnaG",
  email: "ana.garcia@example.com",
  phone: "+34 612 345 678",
  bio: "Estudiante de Psicología, amante de los libros y el yoga. Buscando compañeros de piso para crear un ambiente acogedor y divertido.",
  avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
  darkMode: false,
};

export {
  roomiesData,
  eventsData,
  pisoData,
  tasksData,
  expensesData,
  shoppingItemsData,
  userProfileData,
};
